### ISSUE TITLE
MessagePayloadBuilder does not work if hostname undefined

### ISSUE THREAD

**Issue by ianbamforth** [jsendnsca/jsendnsca#22]
I'm trying to use this inside AWS Lambda code, and it bombs out with: 

    {
      "errorMessage": "java.net.UnknownHostException: ip-10-0-149-225: ip-10-0-149-225: unknown error",
      "errorType": "com.googlecode.jsendnsca.MessagePayload$UnknownHostRuntimeException",
      "stackTrace": [
        "com.googlecode.jsendnsca.MessagePayload.setHostname(MessagePayload.java:105)",
        "com.googlecode.jsendnsca.MessagePayload.useLocalHostname(MessagePayload.java:90)",
        "com.googlecode.jsendnsca.MessagePayload.<init>(MessagePayload.java:52)",
        "com.googlecode.jsendnsca.builders.MessagePayloadBuilder.<init>(MessagePayloadBuilder.java:36)"

Seems the only option is to directly construct a MessagePayload, rather than using the builder, but if there's a way to make the builder usable that would be nice!

**Comment by rajneeshpatel** [comment]
Which version are you using?

**Comment by rajneeshpatel** [comment]
Scratch that, see the issue.

Will look into on Monday and see what can be done to fix.

**Comment by ianbamforth** [comment]
Cheers Raj, much appreciated!

**Comment by rajneeshpatel** [comment]
Ian,

Committed a fix for this and a test so that it doesn't try to construct a payload using the local hostname when using the MessagePayloadBuilder. Hopefully does the trick for you.

Releasing  to maven central so will update this issue with link when complete.

**Comment by rajneeshpatel** [comment]
Uploaded to Maven Central

```xml
<dependency>
  <groupId>com.github.jsendnsca</groupId>
  <artifactId>jsendnsca</artifactId>
  <version>2.1.1</version>
</dependency>
```

Give it a go and let me know if its OK.

**Comment by rajneeshpatel** [comment]
Closing for now as fixed, reopen if not the case
