### ISSUE TITLE
NoClassDefFoundError: com.googlecode.jsendnsca.encryption.Encryption

### ISSUE THREAD

**Issue by rinkeshmodi** [jsendnsca/jsendnsca#23]
I am using 2.1.1 version in my maven project. When i try to initialize NagiosSettings i get java.lang.NoClassDefFoundError: Could not initialize class com.googlecode.jsendnsca.encryption.Encryption. The jar file is present in my WEB_INF/lib

**Comment by rajneeshpatel** [comment]
Can you add a code snippet of how you are intialising NagiosSettings?

**Comment by rinkeshmodi** [comment]
NagiosSettings nagiosSettings = new NagiosSettingsBuilder()
		.withNagiosHost(host)
		.withPort(port)
		.withEncryption(Encryption.XOR)
		.create();

**Comment by rajneeshpatel** [comment]
Pretty sure this is a classpath issue you're experiencing.

I've just tried this in a fresh project, added dependency to 2.1.1 and succesfully run the following method

```java
public static void main(String[] args) {
        NagiosSettings nagiosSettings = new NagiosSettingsBuilder()
                .withNagiosHost("localhost")
                .withPort(5667)
                .withEncryption(Encryption.XOR)
                .create();
    }
```

com.googlecode.jsendnsca.encryption.Encryption is in the jsendnsca-2.1.1.jar so don't believe this is a issue with JSendNSCA.

**Comment by rajneeshpatel** [comment]
Closing issue for now, feel free to comment if you do think is a genuine issue

**Comment by rinkeshmodi** [comment]
Sorry, i had two jars in my classpath which was causing this. Thanks for the support
