### ISSUE TITLE
Source files without license headers

### ISSUE THREAD

**Issue by puntogil** [jsendnsca/jsendnsca#24]
Hi
The following source files are without license headers:
./src/main/java/com/googlecode/jsendnsca/NagiosConfigurationException.java
./src/main/java/com/googlecode/jsendnsca/encryption/BlowfishEncryptor.java
./src/main/java/com/googlecode/jsendnsca/encryption/AESEncryptor.java
./src/test/java/com/googlecode/jsendnsca/encryption/BlowfishEncryptorTest.java

Please, add license headers
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Clarification
Thanks in advance

**Comment by rajneeshpatel** [comment]
Done, thanks

Raj
