### ISSUE TITLE
Java 8 not supported

### ISSUE THREAD

**Issue by NirBY** [jsendnsca/jsendnsca#36]
Getting in compilation:

``` 
com/github/jsendnsca/jsendnsca/2.2.0/jsendnsca-2.2.0.jar!/com/googlecode/jsendnsca/Level.class
    class file has wrong version 55.0, should be 52.0

**Comment by rajneeshpatel** [comment]
Hi 

Latest version is compiled with Java 11

For Java 8, use previous version https://search.maven.org/artifact/com.github.jsendnsca/jsendnsca/2.1.1/jar
